# Generated by Django 5.0.7 on 2024-07-21 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_registration_app', '0006_alter_student_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationDetail',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student_registration_app.student')),
                ('goals', models.TextField(blank=True)),
                ('homework', models.TextField(blank=True)),
            ],
        ),
    ]
