# Generated by Django 5.0.7 on 2024-07-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration_app', '0002_student_confirm_password_student_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default='01-10-2000'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
