# Generated by Django 5.0.7 on 2024-07-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration_app', '0004_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
