# Generated by Django 5.0.7 on 2024-07-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration_app', '0005_alter_student_email_alter_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
